FROM debian:latest

WORKDIR /app

RUN apt-get update && apt-get install -y libgcc-s1 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /data /app/datalake

COPY bin/zed /usr/local/bin/zed

RUN chmod +x /usr/local/bin/zed

RUN zed init  datalake/

CMD ["/bin/sh", "-c", "/usr/local/bin/zed serve /app/datalake/ -l 0.0.0.0:9867"]


