id: 44556677-8899-0011-2233-ddeeff001122
title: AbuseIPDB - Positive Abuse Score
description: Detects IPs with an Abuse Confidence Score greater than 0.
tags:
  - abuseipdb
  - risk
  - reputation
syntax: |
  from 'abuseipdb' | data.abuseConfidenceScore>0
