# Network
ipv4-addr: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
ipv6-addr: "\\b(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}\\b"
domain-name: "\\b(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\\.)+(?!(?:png|jpg|jpeg|gif|pdf|doc|docx|xls|xlsx|ppt|pptx|zip|rar|exe|dll|js|css|html|xml|json|txt|ps1|bat)\\b)[a-zA-Z]{2,6}\\b"
url: "https?:\\/\\/(?:[-\\w.]|(?:%[\\da-fA-F]{2}))+(?:\\/[^\\s]*)?"
mac-addr: "(?:[0-9A-Fa-f]{2}[:-]){5}(?:[0-9A-Fa-f]{2})"
autonomous-system: "\\bAS\\d{1,10}\\b"

# File / Hash
md5: "\\b[a-fA-F0-9]{32}\\b"
sha1: "\\b[a-fA-F0-9]{40}\\b"
sha256: "\\b[a-fA-F0-9]{64}\\b"
sha512: "\\b[a-fA-F0-9]{128}\\b"
ssdeep: "\\b\\d{1,}:[A-Za-z0-9/+]{3,}:[A-Za-z0-9/+]{3,}\\b"
imphash: "\\b[a-fA-F0-9]{32}\\b"
authentihash: "\\b[a-fA-F0-9]{64}\\b"
#file-name: "\\b[\\w,\\s-]+\\.[A-Za-z]{3,4}\\b"

# Identity / PII
email-addr: "\\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}\\b"

# Threats / Mitre
vulnerability: "\\bCVE-\\d{4}-\\d{4,7}\\b"
attack-pattern: "\\bT\\d{4}(?:\\.\\d{3})?\\b"

# System
win-reg-key: "\\b(?:HKLM|HKCU|HKEY_LOCAL_MACHINE|HKEY_CURRENT_USER)\\\\[\\w\\-\\\\]+\\b"
software: "cpe:(?:2\\.3|/)[^\\s]+"

# Crypto
bitcoin-address: "\\b[13][a-km-zA-HJ-NP-Z1-9]{25,34}\\b"
ethereum-address: "\\b0x[a-fA-F0-9]{40}\\b"

# Advanced / Custom
jarm: "\\b[0-9a-f]{62}\\b"
x509-certificate: "\\b[a-fA-F0-9]{40}\\b"

# Location
location: "^[A-Z]{2}$"
