id: 98765432-1234-5678-abcd-ef0123456782
title: Proxycheck - Business IP
description: Identifies IP addresses categorized as Business.
tags:
  - proxycheckio
  - business
syntax: |
  from 'proxycheckio' | over this | yield value | type=='Business'
